### PR TITLE
test: verify fix for #1377

### LINKED ISSUE #1377: Allow procedures with the same name to differ on the number of locals
When compiling the account code, one can wrap the basic wallet example. The issue is that when wrapping said code, there can be name conflicts, for example, the current code [is just an re-export](https://github.com/0xPolygonMiden/miden-base/blob/c29d1def0bca6a66115a6011df1171d836563b90/objects/src/testing/account_code.rs#L69-L72):

```
        # acct proc 0
        export.wallet::receive_asset
        # acct proc 1
        export.wallet::send_asset
```

If the above is changed to:

```
        export.send_asset  # <- note the absence of the local `.1`
            exec.wallet::send_asset
        end
```

The compilation fails with `AccountCodeAssemblerError(ConflictingNumLocals("send_asset"))` when running the following test `cargo test -- executed_transaction_account_delta`. This is a bit annoying, specially because consistently using `proc` for everything is a way of circumventing https://github.com/0xPolygonMiden/miden-vm/issues/1376

### PR DESCRIPTION
**Pull request by bitwalker**
Closes #1377

### CODE REVIEW

File: assembly/src/tests.rs [hunk 1]
```diff
@@ -2486,3 +2486,60 @@ fn test_compiled_library() {
...
+    let context = TestContext::new();
+    let mut mod_parser = ModuleParser::new(ModuleKind::Library);
+    let mod1 = {
+        let source = source_file!(
+            &context,
+            "export.foo.2
+    push.1
+    drop
+end
+"
```
Comment (bobbinth) [inline assembly/src/tests.rs:2501]: nit: formatting is a bit off here.

File: assembly/src/tests.rs [hunk 2]
```diff
@@ -2486,3 +2486,60 @@ fn test_compiled_library() {
...
+    };
+
+    let mod2 = {
+        let source = source_file!(
+            &context,
+            "use.test::mod1
+export.foo
+    exec.mod1::foo
+end
+"
```
Comment (bobbinth) [inline assembly/src/tests.rs:2513]: nit: formatting is a bit off here.

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you! I left a couple of non-blocking nits inline.

File: assembly/src/tests.rs (hunk 1 above)
Comment (bitwalker) [reply assembly/src/tests.rs:2501]: This is intentional, so that diagnostics are rendered properly, you aren't supposed to indent multi-line strings, as the leading whitespace is preserved in the string. I didn't want to fix this up globally for this PR, but we should do that eventually.

File: assembly/src/tests.rs (hunk 2 above)
Comment (bitwalker) [reply assembly/src/tests.rs:2513]: Same here.
