### PR TITLE
Fix kernel ROM multiset check

### LINKED ISSUE #1545: Chiplets bus is broken
- [x] The chiplet virtual table doesn't sum to 1 (due to the kernel ROM part) when there is more than 1 kernel procedure exported.

Failing test:

```rs
#[test]
fn simple_syscall_2() {
    let kernel_source = "
        export.foo
            add
        end
        export.bar
            mul
        end
    ";

    let program_source = "
        begin
            syscall.foo
            syscall.bar
        end";

    // TODO: update and use macro?
    let mut test = Test::new(&format!("test{}", line!()), program_source, false);
    test.stack_inputs = StackInputs::try_from_ints([3, 2, 1]).unwrap();
    test.kernel_source = Some(
        test.source_manager
            .load(&format!("kernel{}", line!()), kernel_source.to_string()),
    );
    test.expect_stack(&[9]);

    test.prove_and_verify(vec![3, 2, 1], false);
}
```

- [ ] The chiplets bus is also broken (some miden-base tests trigger a bug we don't catch in our tests).

### PR DESCRIPTION
**Pull request by plafer**
Closes #1545

I also confirmed that `miden-base` tests pass.

### CODE REVIEW

File: processor/src/chiplets/aux_trace/mod.rs [hunk 1]
```diff
@@ -205,21 +233,33 @@ where
...
-        v.mul_base(addr_delta) + E::from(ONE - addr_delta)
+        let addr_delta = {
+            let addr_nxt = main_trace.chiplet_kernel_addr(row + 1);
+            addr_nxt - addr
+        };
+        let next_row_is_kernel = main_trace.is_kernel_row(row + 1);
+
+        // We want to add a row to the table in 2 cases:
+        // 1. when the next row is still in the kernel table, add the current row only if the
+        //    address column changed
```
Comment (Al-Kindi-0) [inline processor/src/chiplets/aux_trace/mod.rs:244]: nit: the sentence is a bit terse, at least to me, could we simplify it a bit

**Review by Al-Kindi-0 — APPROVED** [review]
Looks great, thank you!
Only a minor nit from me

File: processor/src/chiplets/aux_trace/mod.rs (hunk 1 above)
Comment (plafer) [reply processor/src/chiplets/aux_trace/mod.rs]: Good point; reworded
