### PR TITLE
Fix `ProcessState::get_stack_state()`

### LINKED ISSUE #1744: `ProcessState::get_stack_state` should only return the current context
>I disagree; IMO this is unintuitive behavior. Every since I started used `debug.stack`, I assumed that it was only giving me the current context. For example,

```
proc.foo
    push.100
    # Here I expect the stack to return `[100, 4,3,2,1, ..., 0]` (17 items)
    debug.stack
    drop
end

begin
   push.1.2.3.4
   call.foo
   dropw
end
```

>Even worst, if there is a deep call stack, then printing all the "stored overflows" one after the other without any clear boundary between them is very confusing and arguably useless. IMO the natural behavior is to only return the stack available to the current context (since this is what we care about when debugging a function).
>
>I will open a separate PR to fix this issue.

_Originally posted by @plafer in https://github.com/0xPolygonMiden/miden-vm/pull/1668#discussion_r2027187446_

### PR DESCRIPTION
**Pull request by plafer**
Closes #1744

### CODE REVIEW

**Comment by bobbinth** [comment]
From a brief look, it is not clear to me why we need to make the stack context-aware. Shouldn't `Stack.active_depth` field contain this info already? Basically, what we want to do is get the state of the stack in the current context, right? And I think the depth of the stack in the current context is defined by `active_depth`.

**Comment by plafer** [comment]
To recap, the problem we want to solve is for `Stack::get_state_at()` to return only the elements on the stack in the context associated with the given clock cycle.

What you suggest would work for the current clock cycle in which we end up calling `OverflowTable::append_into()` [here](https://github.com/0xPolygonMiden/miden-vm/blob/2aae3573908c9b07cb0daddceb6754209caae88b/processor/src/stack/mod.rs#L124); we would just need to specify the number of elements to the overflow table (i.e. `active_depth - 16`). However this wouldn't work for any clock cycle other than the current one (i.e. for the `OverflowTable::append_state_into()` case) - so just for that reason I guess we're forced to add context information.

Or maybe I'm missing something still?

**Comment by bobbinth** [comment]
Could we not make sure to save only the relevant part of the overflow table into the `OverflowTable.trace` field? Basically, when we call `OverflowTable::save_current_state()` we could copy over only the elements relevant for the current context. This would also reduce memory usage a bit. Then, each entry in the `OverflowTable.trace` would be truncated to the current context and we'd be able to get it w/o extra modifications.

**Comment by plafer** [comment]
> Basically, when we call OverflowTable::save_current_state() we could copy over only the elements relevant for the current context.

Note: we already do this [here](https://github.com/0xPolygonMiden/miden-vm/blob/2aae3573908c9b07cb0daddceb6754209caae88b/processor/src/stack/overflow.rs#L178-L181). However, in `append_state_into()` [here](https://github.com/0xPolygonMiden/miden-vm/blob/2aae3573908c9b07cb0daddceb6754209caae88b/processor/src/stack/overflow.rs#L155), we're not necessarily getting a row of the requested clock cycle; we're getting the last clock cycle which there was a `push`. But that `push` could have happened in another context, so we still need to check that the context matches. e.g.

```
proc.foo
    # If we call `get_state_at(clk=3)` here, in `append_state_into()
    # we would get the overflow table from clk=2, which is in context 0.
    # However the desired stack state is "empty overflow table"
    swap # clk 3
end

begin
    # push in context 0
    push.1     # clk 
    call.foo   # clk 2
end
```

I'm not sure how to handle this case properly without tracking the context in the overflow table.

**Comment by bobbinth** [comment]
Ah - I see. Could the solution be to always inert an entry into the `trace` when we start a new context? Basically, in `Stack::start_context()` we'd call `OverflowTable::save_current_state()`. This way, when we call `get_state_at()` it'll get the state after we enter new context. This would add some more data to the `trace` but should make the code much simpler.

**Comment by bobbinth** [comment]
> But then the problem becomes in `save_current_state()`, there's no way to know which rows in `active_rows` to include into the trace. Specifically, we want to only include the rows associated with a given `ctx`, but we don't know the context associated with the rows in `active_rows`. (See how in the current implementation of `save_current_state()` we rely on knowing the context for each row).

Could we not pass the `active_depth` into `save_current_state()`? To do this, we'd need to pass it into `OverflowTable::push()` and `OverflowTable::pop()` but I think this would be a much less intrusive change.

Overall, I think the changes in this PR as they currently stand degrade code quality a bit and I think there should be a way to address the issue while improving the code.

**Comment by adr1anh** [comment]
I've been trying to wrap my head around the original construction as well as this PR, but still quite confused but managed to figure the following out. Let me know if this is correct.
- The `OverflowRow`s need to be stored since these are the entries which are inserted/removed from the bus. 
- The `OverflowTable.trace` doesn't correspond to a "trace" in the sense of a STARK trace, but rather a "stack trace" you'd encounter while debugging. Would naming it `stack_states` be more appropriate? Similarly, `stack_enabled` could be `tracing_enabled`. 
- @bobbinth's idea of creating a new stack state when entering a context does seem more intuitive. Overall, it's also not clear why we're managing the tracing in the `OverflowTable` instead of the `Stack`. 
  - Maybe the stack could contain a map `Map<(ctx, clk), Vec<Felt>>` that tracks that entire stack for a given clock cycle within a context. 

Overall, it's hard to give an honest review. I can see the advantage of the current solution to fix the problem for the time being, but it also seems like there should be a cleaner way of achieving this.

**Comment by bobbinth** [comment]
> The `OverflowRow`s need to be stored since these are the entries which are inserted/removed from the bus.

Correct.

> The `OverflowTable.trace` doesn't correspond to a "trace" in the sense of a STARK trace, but rather a "stack trace" you'd encounter while debugging. Would naming it `stack_states` be more appropriate? Similarly, `stack_enabled` could be `tracing_enabled`.

Correct. This is more a result of how thing evolved and I agree that naming here should be improved.

> Overall, it's also not clear why we're managing the tracing in the `OverflowTable` instead of the `Stack`.

The main reason for this is that the top of the stack (i.e., the top 16 elements) at every clock cycle is already stored in `Stack.trace` field. So, `OverflowTable.trace` stores only the overflow portion of the stack.

> Maybe the stack could contain a map `Map<(ctx, clk), Vec<Felt>>` that tracks that entire stack for a given clock cycle within a context.

This would result in quite a bit of data duplication since (as mentioned above) we already have the top 16 elements at every cycle recorded in `Stack.trace` filed.

Overall, I'd rename `OverflowTable.trace` into `OverflowTable.stack_states` but probably keep the rest of the structure as is (at least for now).

**Comment by plafer** [comment]
Ended up rewriting the `OverflowTable`. I realized that a lot of the complexity was due to how it was previously used to generate the auxiliary trace hints; I was able to simplify it a lot.

A few notes:
- `OverflowTable` now stores the `clk` itself rather than taking it as input. 
    - I found this to be cleaner than the previous approach, as we don't actually support pushing at any clock (at least not for history)
- I moved the `OverflowTableRow` to the auxiliary table builder section, where it properly belongs.
  - in the `OverflowStack` we now use a simpler `StackEntry` struct

File: processor/src/stack/overflow.rs [hunk 1]
```diff
@@ -1,211 +1,282 @@
...
+    pub fn pop(&mut self) -> Option<Felt> {
+        // 1. save history
+        if let Some(history) = self.history.as_mut() {
+            history.on_push_or_pop(
+                self.clk,
+                self.overflow
+                    .get(&self.current_ctx)
+                    .unwrap_or(&Vec::new())
+                    .iter()
+                    .map(|e| e.value)
```
Comment (Al-Kindi-0) [inline processor/src/stack/overflow.rs:142]: nit: StackEntry::value

File: processor/src/stack/overflow.rs [hunk 2]
```diff
@@ -1,211 +1,282 @@
...
     }
 
-    // TEST ACCESSORS
+    // PUBLIC MUTATORS
     // --------------------------------------------------------------------------------------------
 
-    #[cfg(test)]
-    pub fn all_rows(&self) -> &[OverflowTableRow] {
-        &self.all_rows
+    /// Indicates that an element was added to or removed from the overflow stack at the current
```
Comment (Al-Kindi-0) [inline processor/src/stack/overflow.rs:236]: nit: Would "Registers" or "Logs" be better than "Indicates" to be better convey the meaning?

File: processor/src/stack/overflow.rs [hunk 3]
```diff
@@ -1,211 +1,282 @@
...
+    /// The `table_before_operation` parameter specifies the state of the overflow stack *before*
+    /// the operation was performed.
+    pub fn on_push_or_pop(&mut self, clk: RowIndex, table_before_operation: Vec<Felt>) {
+        self.save_table_to_history(clk - 1, table_before_operation);
     }
 
-    #[cfg(test)]
-    pub fn active_rows(&self) -> &[usize] {
-        &self.active_rows
+    /// Indicates that a new context was started or a former context was restored at the current
```
Comment (Al-Kindi-0) [inline processor/src/stack/overflow.rs:245]: Same question here

File: processor/src/stack/aux_trace.rs [hunk 4]
```diff
@@ -81,3 +81,35 @@ impl<E: FieldElement<BaseField = Felt>> AuxColumnBuilder<E> for AuxTraceBuilder
         }
     }
 }
+
+// OVERFLOW STACK ROW
+// ================================================================================================
+
+/// A single row in the stack overflow stack. Each row contains the following values:
```
Comment (Al-Kindi-0) [inline processor/src/stack/aux_trace.rs:88]: Is this intentional "stack overflow stack"?

**Review by Al-Kindi-0 — APPROVED** [review]
Looks great!

File: processor/src/stack/overflow.rs [hunk 5]
```diff
@@ -1,211 +1,282 @@
...
+        match self.last_clk_in_history() {
+            Some(last_clk_in_history) => {
+                if target_clk > last_clk_in_history {
+                    None
+                } else {
+                    for (range, state) in self.history.iter() {
+                        if range.contains(&target_clk) {
+                            return Some(state.iter().rev());
+                        }
+                    }
```
Comment (Al-Kindi-0) [inline processor/src/stack/overflow.rs:224]: nit: could we use "iter().find(...)" ?

File: processor/src/stack/overflow.rs [hunk 6]
```diff
@@ -1,211 +1,282 @@
...
-    /// A flag which specifies whether we should record the full state of the overflow table
-    /// whenever an update happens. This is set to true only when executing programs for debug
-    /// purposes.
-    trace_enabled: bool,
-    /// Holds the address (the clock cycle) of the row at to top of the overflow table. When
-    /// entering new execution context, this value is set to ZERO, and thus, will differ from the
-    /// row address actually at the top of the table.
-    last_row_addr: Felt,
+pub struct OverflowStack {
+    overflow: BTreeMap<ContextId, Vec<StackEntry>>,
```
Comment (bobbinth) [inline processor/src/stack/overflow.rs:41]: How does a `BTreeMap` work with syscalls? When we make a syscall, we'd insert an entry into here with `ContextId=0`, right? But if we also an overflow entries for the initial root context, wouldn't they get overwritten?

If so, a solution could be to change this to `Vec<(ContextId, Vec<StackEntry>)` or maybe even just `Vec<Vec<StackEntry>>`. This should work because contexts work like a stack - i.e.,

- When entering a new context an empty `Vec<StackEntry>` would be pushed onto the `overflow` vector.
- When existing a context, the top `Vec<StackEntry>` will be discarded (this top stack entry should be empty at the time of exit, or this will be an error).

**Review by bobbinth — COMMENTED** [review]
Thank you! I like this approach a lot! I left a couple of comments inline - the main one is about how we handle stack overflow in the context of syscalls. It seems to me that using a `BTreeMap` for keeping track of context may cause issues there.

File: processor/src/stack/overflow.rs (hunk 2 above)
Comment (plafer) [reply processor/src/stack/overflow.rs:236]: Switched to "Registers"

File: processor/src/stack/aux_trace.rs (hunk 4 above)
Comment (plafer) [reply processor/src/stack/aux_trace.rs:88]: Oops - fixed to "stack overflow table"

File: processor/src/stack/overflow.rs (hunk 5 above)
Comment (plafer) [reply processor/src/stack/overflow.rs:224]: Good idea - switched to using `find()`

File: processor/src/stack/tests.rs [hunk 7]
```diff
@@ -198,7 +197,8 @@ fn start_restore_context() {
     stack.advance_clock();
 
     // start context
-    stack.start_context();
+    let new_ctx = (stack.clk.as_u32() + 1).into();
```
[the remark this answers is not in the document]
Comment (plafer) [reply processor/src/stack/tests.rs:200]: That method is only defined in `System` so we can't use it here

File: processor/src/stack/overflow.rs (hunk 6 above)
Comment (plafer) [reply processor/src/stack/overflow.rs:41]: Good point; I added 2 tests to cover this use case, and switched to effectively `BTreeMap<ContextId, Vec<Vec<StackEntry>>>`; except that to make this more readable, I renamed `OverflowStack` to `OverflowTable`, and now `OverflowStack = Vec<StackEntry>`.

Also as discussed offline, I believe I had the "off by 1" wrong for `start/restore_context`: I now consider a `CALL` or associated `END` operation as being part of the new context (as I think it's the correct interpretation to have). This removed the need for the distinction between how `start/restore_context()` and `push/pop()` write to history.

File: processor/src/stack/mod.rs [hunk 8]
```diff
@@ -263,46 +265,48 @@ impl Stack {
...
         const START_POSITION: usize = 1;
 
         self.shift_left_no_helpers(START_POSITION);
 
         // reset the helper columns to their default value, and write those to the trace in the next
         // row.
-        let (next_depth, next_overflow_addr) = self.start_context();
+        let next_depth = self.start_context(ctx);
+
         // Note: `start_context()` reset `active_depth` to 16, and `overflow.last_row_addr` to 0.
```
[the remark this answers is not in the document]
Comment (plafer) [reply processor/src/stack/mod.rs:277]: fixed

File: processor/src/stack/overflow.rs [hunk 9]
```diff
@@ -1,211 +1,282 @@
...
-        // last row address points to the next row in the current execution context.
-        let removed_value = last_row.val;
-        self.last_row_addr = last_row.prev;
-
-        if self.trace_enabled {
-            // insert a copy of the current table state into the trace
-            self.save_current_state(clk);
+    /// Appends the values from the overflow stack at the given clock cycle to the end of the
+    /// provided vector.
+    pub fn append_into_at_clk(&self, clk: RowIndex, target: &mut Vec<Felt>) {
```
[the remark this answers is not in the document]
Comment (plafer) [reply processor/src/stack/overflow.rs:73]: Agreed - applied both suggestions

File: processor/src/stack/overflow.rs [hunk 10]
```diff
@@ -1,211 +1,282 @@
...
+            history.on_push_or_pop(
+                self.clk,
+                self.overflow
+                    .get(&self.current_ctx)
+                    .unwrap_or(&Vec::new())
+                    .iter()
+                    .map(|e| e.value)
+                    .collect(),
+            )
         }
```
[the remark this answers is not in the document]
Comment (plafer) [reply processor/src/stack/overflow.rs:145]: The distinction between `start_or_restore_context` and `on_push_or_pop` was naturally removed (see https://github.com/0xPolygonMiden/miden-vm/pull/1753#discussion_r2054918341). I then have a single function `save_stack_to_history_before_clk()` which I believe better conveys the behavior that we're storing everything *before* the given clock cycle?

Let me know what you think.

[the remark this answers is not in the document]
Comment (adr1anh) [reply processor/src/stack/overflow.rs]: Sounds good!

File: processor/src/stack/mod.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (adr1anh) [reply processor/src/stack/mod.rs:277]: Nit: I think the other `reset` was meant to change

**Review by adr1anh — APPROVED** [review]

File: processor/src/stack/overflow.rs [hunk 11]
```diff
@@ -1,211 +1,414 @@
...
+                .collect();
+
+            // Note: we do the `history.is_some()` and `history.unwrap()` instead of matching to
+            // satisfy the borrow checker (due to the call to `get_current_overflow_stack()` which
+            // borrows `self` immutably).
+            self.history
+                .as_mut()
+                .unwrap()
+                .save_stack_to_history_before_clk(clk, table_before_pop);
+        }
```
Comment (bobbinth) [inline processor/src/stack/overflow.rs:219]: This code seems to be repeated 4 times - why not make it into a separate helper method. For example:
```rust
fn save_stack_to_history(&mut self) {
    let clk = self.clk;
    if self.history.is_some() {
        let table_before_op: Vec<Felt> = self
            .get_current_overflow_stack()
            .iter()
            .map(OverflowStackEntry::value)
            .collect();
        
        self.history
            .as_mut()
            .unwrap()
            .save_stack_to_history_before_clk(clk, table_before_op);
    }
}
```

File: processor/src/stack/overflow.rs [hunk 12]
```diff
@@ -1,211 +1,414 @@
...
+/// The events which update the overflow table history are:
+/// - `push` operation,
+/// - `pop` operation,
+/// - a new context is started,
+/// - a former context is restored.
+#[derive(Debug)]
+struct OverflowTableHistory {
+    /// Stores the full state of the overflow table at every clock cycle. Formally, if `clk <
+    /// last_transition_clk`, then there is exactly one range in the history which contains `clk`.
+    history: Vec<(RangeInclusive<RowIndex>, Vec<Felt>)>,
```
Comment (bobbinth) [inline processor/src/stack/overflow.rs:331]: This works, but I wonder if it would be simpler to track the states simply as `Vec<(RowIndex, Vec<Felt>)`, where `RowIndex` would be the clock cycle at which the new stack state took effect. For example:
```
(0, vec![]),
(3, vec[0]), // push(1) was executed at clock cycle 2
(7, vec[]),  // drop was executed at clock cycle 6
```
if we want to get the value of the values on the overflow stack at cycle 5, all we need to do is find the first entry that is smaller than or equal to 5. And we should be able to do this using simple binary search (i.e., no need to scan the whole history using `.find()`).

File: processor/src/stack/overflow.rs [hunk 13]
```diff
@@ -1,211 +1,414 @@
...
-    pub fn all_rows(&self) -> &[OverflowTableRow] {
-        &self.all_rows
+    /// Returns the overflow table at the given clock cycle in the active context at that clock
+    /// cycle if present in the history, otherwise returns `None`.
+    ///
+    /// That is, if the target clock cycle is greater than the last clock cycle at which the
+    /// history was updated, the method returns `None`.
+    ///
+    /// The first element returned by the iterator is the top of the overflow table.
+    pub fn get_at(&self, target_clk: RowIndex) -> Option<impl Iterator<Item = &Felt>> {
```
Comment (bobbinth) [inline processor/src/stack/overflow.rs:350]: Related to the previous comment, if we store the state after a given operation, this could be simplified a bit and the signature could be:
```rust
pub fn get_at(&self, target_clk: RowIndex) -> &[Felt]
```

**Review by bobbinth — COMMENTED** [review]
Thank you! Looks good! Overall, this works but it does seem like we may be able to simplify the code a bit. I left a few suggestions inline.

File: processor/src/stack/overflow.rs [hunk 14]
```diff
@@ -1,211 +1,414 @@
...
+        };
+
         Self {
-            all_rows: Vec::new(),
-            active_rows: Vec::new(),
-            trace: BTreeMap::new(),
-            trace_enabled: enable_trace,
-            last_row_addr: ZERO,
+            overflow,
+            current_ctx: ContextId::default(),
```
[the remark this answers is not in the document]
Comment (plafer) [reply processor/src/stack/overflow.rs:113]: Removed

File: processor/src/stack/overflow.rs (hunk 11 above)
Comment (plafer) [reply processor/src/stack/overflow.rs:219]: Done

File: processor/src/stack/overflow.rs (hunk 12 above)
Comment (plafer) [reply processor/src/stack/overflow.rs:267]: I played around with it a bit and ultimately found that representation harder to reason about the off-by-1 errors, since ranges are implicit rather than explicitly represented. For one, as I understand it, your example is off by one - I would expect:

```
(0, vec![]),
(2, vec[0]), // push(1) was executed at clock cycle 2
(6, vec[]),  // drop was executed at clock cycle 6
```

That is, if `push(1)` occurs at clock cycle 2, then the result of that push is recorded in the same clock cycle (even though it is stored in the `next` row in the trace). But then the logic to retrieve the the right overflow stack (based on [`slice::partition_point`](https://doc.rust-lang.org/std/primitive.slice.html#method.partition_point)) was less intuitive to me.

> And we should be able to do this using simple binary search (i.e., no need to scan the whole history using .find()).

I updated the current implementation to use a binary search instead of `find()`

File: processor/src/stack/overflow.rs (hunk 13 above)
Comment (plafer) [reply processor/src/stack/overflow.rs:286]: We can't return a slice in either case, since we don't store the `Vec<Felt>` in the correct order - we need to `rev()` before returning. So I think the current signature is more flexible, since we can change the internal representation (e.g. by flipping the order of elements stored) without breaking the API. Also, it works well with the `append_into()` pattern that we have (such that we only need to do `result.extend(iterator)`).

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you! I left a couple of small comments inline and also one comment about potential simplification to the overflow history. If the approach I suggested doesn't work, feel free to merge as is.

File: processor/src/stack/overflow.rs [hunk 15]
```diff
@@ -1,211 +1,381 @@
...
+    }
+}
+
+/// Represents an overflow stack at a given context.
+///
+/// All contexts other than the root context can never be re-entered, so can have at most a single
+/// instance of `OverflowStack` per context. However, the root context can be re-entered with a
+/// syscall, and so can have up to 2 instances of `OverflowStack` per context.
+#[derive(Debug, Default)]
+struct OverflowStack {
```
[the remark this answers is not in the document]
Comment (plafer) [reply processor/src/stack/overflow.rs:36]: Removed

File: processor/src/stack/overflow.rs [hunk 16]
```diff
@@ -1,211 +1,381 @@
...
-    ///
-    /// # Panics
-    /// Panics when this overflow table was not initialized with `enable_trace` set to true.
-    pub fn append_state_into(&self, target: &mut Vec<Felt>, clk: u64) {
-        assert!(self.trace_enabled, "overflow trace not enabled");
-        if let Some(x) = self.trace.range(0..=clk).last() {
-            for item in x.1.iter().rev() {
-                target.push(*item);
-            }
+    fn save_stack_to_history(&mut self) {
```
[the remark this answers is not in the document]
Comment (plafer) [reply processor/src/stack/overflow.rs:238]: Done

File: processor/src/stack/overflow.rs [hunk 17]
```diff
@@ -1,211 +1,381 @@
...
+    /// - if the overflow stack for the current context is not empty.
+    ///   - i.e. this should be checked before calling this function.
+    pub fn restore_context(&mut self) {
+        // 1. save history
+        self.save_stack_to_history();
+
+        // 2. pop the last overflow stack for the current context, and make sure it is empty.
+        let overflow_stack_for_ctx =
+            self.overflow.pop().expect("no overflow stack at the end of a context");
+        assert!(overflow_stack_for_ctx.is_empty());
```
[the remark this answers is not in the document]
Comment (plafer) [reply processor/src/stack/overflow.rs:209]: done

File: processor/src/stack/overflow.rs (hunk 12 above)
Comment (plafer) [reply processor/src/stack/overflow.rs]: Ah yes - I incorporated the suggestion (which does indeed simplify things!) - except for "my version" of the off-by ones as detailed in my previous comment. Specifically, for your example trace, your implementation would lead to:

```
get_at(0) -> []
get_at(1) -> []
get_at(2) -> [] // ERROR: want [0]
get_at(3) -> [0]
get_at(4) -> [0]
get_at(5) -> [0]
get_at(6) -> [0] // ERROR: want []
```

That is, the state of the overflow table should reflect the change of a push/pop in *the same* clock cycle as the push/pop operation - not the subsequent one. If for some reason this is not the current state of the VM's semantics, then we should open a new issue and discuss this there, as I would find these semantics to be unintuitive.
