### PR TITLE
fix(assembly): Added Range queries for interval checks

### LINKED ISSUE #535: Use core Range for interval checks
We should use [Range](https://doc.rust-lang.org/std/ops/struct.Range.html) for interval checks, given their nature to reduce chances of error for repeated checks, and will cause no overhead due to their efficient implementation

They are also idiomatic to Rust and expected in many libraries and trait implementations

_Originally posted by @vlopes11 in https://github.com/maticnetwork/miden/pull/526#discussion_r1027853113_

### PR DESCRIPTION
**Pull request by amankrx**
## Describe your changes
Fixes #535 

Currently added the Range queries in the assembly. I have just changed two of those functions. Please do update if I'll have to make any more changes here, or any corrections to these functions. 
And, Sorry I took a long time to create this PR.

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

### CODE REVIEW

File: assembly/src/assembler/instruction/mod.rs [hunk 1]
```diff
@@ -335,14 +335,18 @@ fn push_felt(span: &mut SpanBuilder, value: Felt) {
 
 /// Returns an error if the specified value is smaller than or equal to min or greater than or
 /// equal to max. Otherwise, returns Ok(()).
-fn validate_param<I: Ord + Into<u64>>(value: I, min: I, max: I) -> Result<(), AssemblyError> {
-    if value < min || value > max {
+fn validate_param<I: Copy + Ord + Into<u64>>(
```
Comment (vlopes11) [inline assembly/src/assembler/instruction/mod.rs:338]: We could benefit from the canonical range components by using a generic [RangeBounds](https://doc.rust-lang.org/core/ops/trait.RangeBounds.html) argument. This way, this call that might seem ambiguous

`validate_param(value, 10, 20)`

Because it could represent either `10..20` or `10..=20` will be unmistakably represented as either one of the two

`validate_param(value, 10..20)`
`validate_param(value, 10..=20)`.

The function signature would look something like

```rust
use core::ops::{RangeBounds, Bound};

fn bound_into_u64<I>(bound: Bound<&I>) -> u64
where
    I: Clone + Into<u64>,
{
    match bound {
        Bound::Excluded(i) => i.clone().into().saturating_sub(1),
        Bound::Included(i) => i.clone().into(),
        Bound::Unbounded => u64::MAX,
    }
}

fn parse_checked_param<I, R>(value: I, range: R) -> Result<(), AssemblyError>
where
    I: Ord + Clone + Into<u64>,
    R: RangeBounds<I>
{
    range.contains(&value).then_some(()).ok_or_else(||
        AssemblyError::param_out_of_bounds(
            value.into(),
            bound_into_u64(range.start_bound()),
            bound_into_u64(range.end_bound()),
        )
    )
}
```

It's always better to avoid adding `Copy` as requirement because:

- A type that implements `Copy` properly will also copy on a clone call. Since this is a native type (`u64`), then it implements copy properly and we don't need to explicitly require it.
- `Copy` is super restrictive and might impose a limitation that we don't really need to impose.

**Review by vlopes11 — CHANGES_REQUESTED** [review]
Thanks for the contribution!

The general idea is to make the API calls to this internal function unambiguous, meaning they should not depend on context to be understood as either included or excluded ranges.

It is beneficial also to update the error message from `AssemblyError` to always say explicitly that we are reporting (if we take the suggested code as reference) included bounds.

File: assembly/src/assembler/instruction/mod.rs (hunk 1 above)
Comment (amankrx) [reply assembly/src/assembler/instruction/mod.rs:338]: Oh... Okay. Thanks for the detailed review. 
The `bound_into_included_u64` can be used in different functions. So, maybe we can separately put this function in a different module to easily access it over different functions.

Comment (amankrx) [reply assembly/src/assembler/instruction/mod.rs:338]: Hey, I had made the requested changes, and I was wondering if the `bound_into_included_u64` can be separated into a different module to access it whenever needed.

Comment (amankrx) [reply assembly/src/assembler/instruction/mod.rs:338]: Hey @vlopes11, Did you checked the above question? I have already made the changes. But if it is possible and suitable to separate `bound_into_included_u64` in a different helper module for eg? It would be easier to make multiple function calls.

Comment (vlopes11) [reply assembly/src/assembler/instruction/mod.rs:338]: @amankrx that would a good case if the function is expected to be used somewhere else. I think the only applicable place is in this module; also, it is a function because it is called twice, so we avoid duplication.

**Comment by amankrx** [comment]
Hey @vlopes11, I updated the commit, please let me know if I have to update anything else

File: assembly/src/parsers/field_ops.rs [hunk 2]
```diff
@@ -178,5 +178,5 @@ fn parse_bit_len_param(op: &Token, param_idx: usize) -> Result<u8, ParsingError>
 }
 
 fn parse_imm_value(op: &Token) -> Result<Felt, ParsingError> {
-    Ok(Felt::new(parse_checked_param::<u64>(op, 1, 0, Felt::MODULUS - 1)?))
+    Ok(Felt::new(parse_checked_param::<u64, _>(op, 1, 0..=(Felt::MODULUS - 1))?))
```
Comment (vlopes11) [inline assembly/src/parsers/field_ops.rs:181]: optional nit: instead of making an inclusive range check - 1, we can `0..Felt::MODULUS`

File: assembly/src/assembler/instruction/mod.rs [hunk 3]
```diff
@@ -337,12 +338,30 @@ fn push_felt(span: &mut SpanBuilder, value: Felt) {
...
-    }
+fn validate_param<I, R>(value: I, range: R) -> Result<(), AssemblyError>
+where
+    I: Ord + Clone + Into<u64>,
+    R: RangeBounds<I>,
+{
+    range.contains(&value).then_some(()).ok_or_else(|| {
+        AssemblyError::param_out_of_bounds(
+            value.into(),
+            bound_into_included_u64(range.start_bound()),
```
Comment (vlopes11) [inline assembly/src/assembler/instruction/mod.rs:363]: optional nit: the error report might be wrong if the start bound is `Bound::Unbounded` because it will display `u64::MAX` instead of `0`

File: assembly/src/parsers/mod.rs [hunk 4]
```diff
@@ -323,14 +326,25 @@ fn parse_param<I: core::str::FromStr>(op: &Token, param_idx: usize) -> Result<I,
     Ok(result)
 }
 
+/// A helper function that specifies if the Range Query is inclusive or exclusive.
+fn bound_into_included_u64<I>(bound: Bound<&I>) -> u64
```
Comment (vlopes11) [inline assembly/src/parsers/mod.rs:330]: optional nit: might be overkill to promote this function to the root module since it is used both in `parsers` and `instruction`, but on the other hand we should avoid repeating code.

**Review by vlopes11 — CHANGES_REQUESTED** [review]
couple of last questions before we merge

File: assembly/src/assembler/instruction/mod.rs (hunk 3 above)
Comment (amankrx) [reply assembly/src/assembler/instruction/mod.rs:363]: Ohh... Somehow I missed it. Anyway, what should be the most suitable way to achieve this?
- Should I add an extra boolean parameter specifying if it is a start bound? That way it is easy to get the correct Unbounded data. But it leaves some space for ambiguity. [I went ahead with this]
- Next would be to return a start and end bounds vector after passing the RangeBounds itself. But again, it would be ambiguous.
- Or is there any other better way to do it?

File: assembly/src/parsers/mod.rs (hunk 4 above)
Comment (amankrx) [reply assembly/src/parsers/mod.rs]: I moved it to utils. That's what I asked earlier. If we should move this function somewhere else to be easily accessed across different modules.

File: assembly/src/assembler/instruction/mod.rs (hunk 3 above)
Comment (vlopes11) [reply assembly/src/assembler/instruction/mod.rs]: A parameter will work just fine as it is hardcoded so the compiler will just optimize it away

File: assembly/src/parsers/mod.rs (hunk 4 above)
Comment (vlopes11) [reply assembly/src/parsers/mod.rs]: Yes, that would be the right choice as we call it in multiple places

**Review by vlopes11 — APPROVED** [review]
LGTM! Thanks for the contribution
